In [ ]:
#NLP Project (Pipeline -> Text Cleaning)

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
df = pd.read_csv('train.txt',sep=';',header=None, names=['text','emotions']) #in csv file we dont have comas so
#what we did here is we read our txt file as csv file and separated it with the comas
#and created two cols text and emotions

In [ ]:
df.head()

                                                text emotions
0                            i didnt feel humiliated  sadness
1  i can go from feeling so hopeless to so damned...  sadness
2   im grabbing a minute to post i feel greedy wrong    anger
3  i am ever feeling nostalgic about the fireplac...     love
4                               i am feeling grouchy    anger

In [ ]:
df.isnull().sum() #to check whether we have null values or not

text        0
emotions    0
dtype: int64

In [ ]:
#now checking how many unique emotions we have
df['emotions'].unique()

array(['sadness', 'anger', 'love', 'surprise', 'fear', 'joy'],
      dtype=object)

In [ ]:
#now creating a dictionory where these emotions are converted into 0 based indexing
unique_emotions= df['emotions'].unique() #first created a array
emotion_numbers={}
i=0
for emo in unique_emotions:
    emotion_numbers[emo]=i
    i=i+1
df['emotions']=df['emotions'].map(emotion_numbers)

In [ ]:
df

                                                    text  emotions
0                                i didnt feel humiliated         0
1      i can go from feeling so hopeless to so damned...         0
2       im grabbing a minute to post i feel greedy wrong         1
3      i am ever feeling nostalgic about the fireplac...         2
4                                   i am feeling grouchy         1
...                                                  ...       ...
15995  i just had a very brief time in the beanbag an...         0
15996  i am now turning and i feel pathetic that i am...         0
15997                     i feel strong and good overall         5
15998  i feel like this was such a rude comment and i...         1
15999  i know a lot but i feel so stupid because i ca...         0

[16000 rows x 2 columns]

In [ ]:
#converting all texts in lower case
df['text'] = df['text'].apply(lambda x: x.lower())
df

                                                    text  emotions
0                                i didnt feel humiliated         0
1      i can go from feeling so hopeless to so damned...         0
2       im grabbing a minute to post i feel greedy wrong         1
3      i am ever feeling nostalgic about the fireplac...         2
4                                   i am feeling grouchy         1
...                                                  ...       ...
15995  i just had a very brief time in the beanbag an...         0
15996  i am now turning and i feel pathetic that i am...         0
15997                     i feel strong and good overall         5
15998  i feel like this was such a rude comment and i...         1
15999  i know a lot but i feel so stupid because i ca...         0

[16000 rows x 2 columns]

In [ ]:
#Removing punctuations
import string
def remove_punc(txt):
  return txt.translate(str.maketrans('','',string.punctuation))
df['text'] = df['text'].apply(remove_punc)

In [ ]:
# Remove numbers
def remove_num(txt):
  new=""
  for i in txt:
    if not i.isdigit():
      new=new+i
  return new
df['text'] = df['text'].apply(remove_num)

In [ ]:
# Remove emogis and special char
def remove_emojis(txt):
  new=""
  for i in txt:
    if i.isascii(): # move data to new only if i has a ascii value and as emojis dont have any ascii value it will be terminated
      new=new+i
  return new
df['text'] = df['text'].apply(remove_emojis)

In [ ]:
# Remove stopwords
# to remove the stopwords we have to use a library and that is NLTK
import nltk
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
nltk.download('stopwords')
nltk.download('punkt')# is a library which toeknizes your words (means simply , it is used for tokenization)

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.
[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.

True

In [ ]:
# to see the set of stopwords
stop_words = set(stopwords.words('english'))
stop_words

{'a',
 'about',
 'above',
 'after',
 'again',
 'against',
 'ain',
 'all',
 'am',
 'an',
 'and',
 'any',
 'are',
 'aren',
 "aren't",
 'as',
 'at',
 'be',
 'because',
 'been',
 'before',
 'being',
 'below',
 'between',
 'both',
 'but',
 'by',
 'can',
 'couldn',
 "couldn't",
 'd',
 'did',
 'didn',
 "didn't",
 'do',
 'does',
 'doesn',
 "doesn't",
 'doing',
 'don',
 "don't",
 'down',
 'during',
 'each',
 'few',
 'for',
 'from',
 'further',
 'had',
 'hadn',
 "hadn't",
 'has',
 'hasn',
 "hasn't",
 'have',
 'haven',
 "haven't",
 'having',
 'he',
 "he'd",
 "he'll",
 "he's",
 'her',
 'here',
 'hers',
 'herself',
 'him',
 'himself',
 'his',
 'how',
 'i',
 "i'd",
 "i'll",
 "i'm",
 "i've",
 'if',
 'in',
 'into',
 'is',
 'isn',
 "isn't",
 'it',
 "it'd",
 "it'll",
 "it's",
 'its',
 'itself',
 'just',
 'll',
 'm',
 'ma',
 'me',
 'mightn',
 "mightn't",
 'more',
 'most',
 'mustn',
 "mustn't",
 'my',
 'myself',
 'needn',
 "needn't",
 'no',
 'nor',
 'not',
 'now',
 'o',
 'of',
 'off',
 'on',
 'once',
 'only',
 'or',
 'other',
 'our',
 'ours',
 'ourselves',
 'out',
 'over',
 'own',
 're',
 's',
 'same',
 'shan',
 "shan't",
 'she',
 "she'd",
 "she'll",
 "she's",
 'should',
 "should've",
 'shouldn',
 "shouldn't",
 'so',
 'some',
 'such',
 't',
 'than',
 'that',
 "that'll",
 'the',
 'their',
 'theirs',
 'them',
 'themselves',
 'then',
 'there',
 'these',
 'they',
 "they'd",
 "they'll",
 "they're",
 "they've",
 'this',
 'those',
 'through',
 'to',
 'too',
 'under',
 'until',
 'up',
 've',
 'very',
 'was',
 'wasn',
 "wasn't",
 'we',
 "we'd",
 "we'll",
 "we're",
 "we've",
 'were',
 'weren',
 "weren't",
 'what',
 'when',
 'where',
 'which',
 'while',
 'who',
 'whom',
 'why',
 'will',
 'with',
 'won',
 "won't",
 'wouldn',
 "wouldn't",
 'y',
 'you',
 "you'd",
 "you'll",
 "you're",
 "you've",
 'your',
 'yours',
 'yourself',
 'yourselves'}

In [ ]:
len(stop_words)

198

In [ ]:
#now removing stop words
df.loc[1]['text'] # to see the data

'i can go from feeling so hopeless to so damned hopeful just from being around someone who cares and is awake'

In [ ]:
# as we have the list of stop words and will convert it into array
def remove(txt):
  words = txt.split() #here we have to use word_tokenize instead of split (we are using split as it is giving some error in google colab)
  cleaned = []
  for i in words:
    if not i in stop_words:
      cleaned.append(i)
  return ' '.join(cleaned)
df['text'] = df['text'].apply(remove)
# note: split and tokenize are both diff

In [ ]:
# now seeing the same sentence after removing stopwords
df.loc[1]['text']

'go feeling hopeless damned hopeful around someone cares awake'

In [ ]:
# This is all about data preprocessing in NLP

In [ ]:
# now heading to the project

In [ ]:
df.head()

                                                text  emotions
0                              didnt feel humiliated         0
1  go feeling hopeless damned hopeful around some...         0
2          im grabbing minute post feel greedy wrong         1
3  ever feeling nostalgic fireplace know still pr...         2
4                                    feeling grouchy         1

In [ ]:
#doing train_test split
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(df['text'],df['emotions'],test_size=0.2,random_state=42)

In [ ]:
X_train

676      refers course though cant help feeling somehow...
12113                im starting feel im suffering fatigue
7077     feel like probably would liked book little bit...
13005                                  really feel awkward
12123    im feeling little grumpy today lame weather te...
                               ...
13418    love leave reader feeling confused slightly de...
5390                                         feel delicate
860                          starting feel little stressed
15795             feel stressed tired worn shape neglected
7270         feel someone rude wrongly done something lose
Name: text, Length: 12800, dtype: object

In [ ]:
X_test

8756                             ive made week feel beaten
4660                              feel strategy worthwhile
6095                     feel worthless weak say want find
304                                        feel clever nov
8241                      im moved ive feeling kind gloomy
                               ...
15578    feel useful pulpit find ironic often question ...
5746             dried bladders ready day im feeling brave
6395                             feel thrilled matter days
7624     woke morning text mr c declaring walking work ...
15245                                            feel dumb
Name: text, Length: 3200, dtype: object

In [ ]:
# vectorization (converting x_train and x_test into vectors)
from sklearn.feature_extraction.text import TfidfVectorizer, CountVectorizer

#first doing with count vectorizer(bag of words)
cv = CountVectorizer()
X_train_cv = cv.fit_transform(X_train)
X_test_cv = cv.transform(X_test)

In [ ]:
from sklearn.naive_bayes import MultinomialNB # for text classification we use Myultinomial Naive Bayes algo
from sklearn.metrics import accuracy_score
model = MultinomialNB()
model.fit(X_train_cv,y_train)

MultinomialNB()

In [ ]:
y_pred = model.predict(X_test_cv)
print(accuracy_score(y_test,y_pred))

0.768125

In [ ]:
y_pred

array([0, 5, 0, ..., 5, 5, 0])

In [ ]:
# now doing with TF-IDF
cv = TfidfVectorizer()
X_train_cv = cv.fit_transform(X_train)
X_test_cv = cv.transform(X_test)

In [ ]:
model = MultinomialNB() # for text classification we use Myultinomial Naive Bayes algo
model.fit(X_train_cv,y_train)

MultinomialNB()

In [ ]:
y_pred = model.predict(X_test_cv)
print(accuracy_score(y_test,y_pred))

0.6609375

In [ ]:
# doing TF-IDF With logistic regression

In [ ]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression(max_iter=1000)
model.fit(X_train_cv,y_train)

LogisticRegression(max_iter=1000)

In [ ]:
y_pred = model.predict(X_test_cv)
print(accuracy_score(y_test,y_pred))

0.8628125

In [ ]:
# this is all about this project